### ISSUE TITLE
Dynamic Public Keys

### ISSUE THREAD

**Issue by JonesWest** [richnologies/ngx-stripe#259]
The docs has a short section about using dynamic public keys: https://ngx-stripe.dev/docs/setup-application, it refers to using the injectStripe method, and an example for it. However, the example is not do be found anywhere. 

I've tried the following: 

```
imports: [
...
     NgxStripeModule.forRoot(),
...
]
```
Notice no key in the module registration. 
In my component I then: 

```
constructor(...){
     injectStripe(environment.stripePublishableKey);
}
```

But I get this error as soon as I begin using any Stripe directive: 
```
TypeError: Cannot read properties of undefined (reading 'elements')
    at StripeService.elements (ngx-stripe.mjs:435:28)
    at StripeElementsService.elements (ngx-stripe.mjs:689:43)
    at ngx-stripe.mjs:1407:63
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (asyncToGenerator.js:3:1)
    at _next (asyncToGenerator.js:22:1)
    at asyncToGenerator.js:27:1
    at new ZoneAwarePromise (zone.js:2611:25)
    at asyncToGenerator.js:19:1
    at StripeCardGroupDirective.ngOnChanges (ngx-stripe.mjs:1410:30)

```

**Comment by lcottingham** [comment]
You can change the key on the stripe service dynamically. Just defer the loading of the stripe element until you have the dynamic key you wish to use.

```
protected stripeService = inject(StripeService)
ngOnInit() {
  const key = this.keyService.fetchDynamicKey()
  this.stripeService.changeKey(key)
}

So long as your server side is using the correct counterpart secret key to the publishable one on the client side, the `confirm()` should work.
